### PR TITLE
Pypi packaging

### PR DESCRIPTION
**Pull request by SP5D**
Ok, it's ready and available by ```pip install x11pygrid```

As you can see, I've added prefix to the project name. That was the only way to upload package – pygrid is already used twice. The first package is CLI for AWS, GCP and Azure; The second is something about Deep Learning. To prevent illegal name duplication and mess – I've decided to add ```x11``` prefix. IMHO it's the best solution.

---

If you're thinking about changing repo name to x11pygrid (to preserve stars etc.), it could be good idea to make also new repo with old name. Just alias which will preserve old external links to the repo ;)

---

I've no idea what are you going to choose. Also, that's many times too big decision to use your previous permission.
Because of that, I'm going to wait with modifications of ```Readme.md```. It may be small... or almost none.

---

It was important for me to preserve continuity of the ```pygrid.py``` history while making this directories rearrangement to make packaging possible. The simplest and surest way to do that was making strange commits step by step. It works, but looking at the separate commits makes no sense.

### CODE REVIEW

**Comment by pkkid** [comment]
This looks great, thanks for these updates.

I'm fine with a name change to make things match nice. I'm not sure if we need to make an empty old repo or not, I thought github would redirect for us, but not positive on that. Do you need me to make that change?

**Comment by SP5D** [comment]
Thanks!

Yes, rename can be done only by repo owner in person. Looks like you've already done it :)

For now, the redirection from pkkid/pygrid to pkkid/x11pygrid works fine. Probably it'll stay fine, but I'm going to watch it in case it's only temporal. It's working out of the box, so I doubt, but it's better to be prepared.

Today or tomorrow I'll update the Readme.

**Comment by matbgn** [comment]
Already a major thanks to your major contribution.

Would it be possible to make installable via pipx so that it will put pygrid in a dedicated, isolated environment for the local user?

For instance like guake (see: https://guake.readthedocs.io/en/latest/user/installing.html#install-from-pypi)

For this I think we only miss some small things:

```bash
$ pipx install x11pygrid
Fatal error from pip prevented installation. Full pip output in file:
    /home/matbgn/.local/pipx/logs/cmd_2022-08-02_17.22.52_pip_errors.log

pip seemed to fail to build package:
    pycairo

Some possibly relevant errors from pip install:
    error: subprocess-exited-with-error
    Package cairo was not found in the pkg-config search path.

Error installing x11pygrid.

``` 

Where a `pip install --user x11pygrid` doesn't have any problem. Any idea on a possible fix?

**Comment by pkkid** [comment]
If it makes you feel better on the redirect working long term, I have another project of I wrote 10ish years ago. Since then my username changed as well as the project itself changed ownership 2 or 3 times and the redirect from it's very first origins still works ok. -- http://github.com/mjs7231/django-dbbackup

**Comment by SP5D** [comment]
@matbgn It's possible, I hope. I'm going to check it out!
Shame to admit, but... thanks for advertising me pipx! I was looking for something like that for a really long time. Since few years I'm using my own small script to do, what's pipx designed for.
Since pipx should be fully compatible with pip, it can be tiny or huge problem. We'll see.

@pkkid Great project! Although I'm more Flask than Django man, I'll remember about it. And maybe push something. But for now (contrary to appearances) I'm busy looking for a good job, so contributing is limited to minimum. Just priorities...

**Comment by SP5D** [comment]
For me (FreeBSD) it's working without problems, so it can be just Linux thing.
```
pipx install x11pygrid 
  installed package x11pygrid 1.0.1, installed using Python 3.9.13
  These apps are now globally available
    - x11pygrid
done!
```

**Comment by matbgn** [comment]
Just made a completely hard fresh install of Linux Mint 21 after trying it on Tuxedo OS -> no more luck.

Does it mean that the complete Linux / Debian-Ubuntu branch is just left as is?

You do not have any idea for this to be fixed? Can you at least reproduce it in a VM and tell me your best guess to investigate on my side? Even I'm not familiar with packaging at all...

At the very least pleased to gave you some king of gift with pipx ;-)

**Comment by SP5D** [comment]
My best guess is a bit brute... but it can work.
I've superficially tested something and it works, but also it should be checked correct way. Ad rem – the problem was pycairo, which is IMHO redundant dependency. Probably old method which was not removed. I'm not sure, maybe I'm in terrible mistake, but... it's working totally fine without pycairo.
It's both ugly and great method of solving such bugs ;)

Today (Aug 3) I'll have no time to check it right. Version without pycairo is already uploaded to testpypi (only) and commited to ```pypi_packaging``` branch, but it need to wait for my tests until tomorrow.
If you have a "minute", you can check it out with:
```python3 -m pip install --user --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple x11pygrid==1.0.2 ```

I don't know how to pipx from testing, but that looks reasonable: https://github.com/pypa/pipx#running-from-source-control 
If I'm right, then branch ```pypi_packaging``` is ready to such use ;)

**Comment by SP5D** [comment]
@matbgn I've done a research. Looks like cairo is common problem and the best solution is (for Ubuntu):
```sudo apt install libcairo2-dev pkg-config python3-dev libgirepository1.0-dev```
Above should allow pipx to install x11pygrid without errors.

Virtualbox doesn't pass complex key combinations as it should (```xev``` shows KeymapNotify instead of standard KeyPress), so the test wasn't full. But what's not mapped to uhid (as I understand), works well. I will test it on few distros from livecd (usb).

**Comment by matbgn** [comment]
Amazing I can confirm that it works like a charm! Thanks

**Comment by SP5D** [comment]
@matbgn Done! For Ubuntu and few other systems ;)

**Pull request merged**
