### PR TITLE
deprecation handling, GObject -> GLib

### PR DESCRIPTION
**Pull request by sivaprakasaman**
Deprecation warning turned to deprecation. Should be handled now. Stable on my computer now. Thanks for all the work! I use this daily.

### CODE REVIEW

**Comment by sivaprakasaman** [comment]
Bump

**Comment by pkkid** [comment]
Ohh sorry, looking now.

**Comment by pkkid** [comment]
Thank you for this!

**Comment by sivaprakasaman** [comment]
My job was easy, thank you for putting in the hard work!!!

**Pull request merged**
